'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useAuthContext} from '@/context/AuthContext';
import {academicRequest,api,AcademicSection,Department} from '@/lib/api';
import Modal from './Modal';
type Member={id:number;name:string;email:string;role:string;status:string};
type Users={total:number;page:number;students:number;professors:number;users:Member[]};
type History={id:number;action:string;detail:string;created_at:string;actor_id:number};
export default function AdminArea(){
 const {user,refreshUser}=useAuthContext();const id=user?.institution_id;const allowed=user?.institution_role==='super_admin';
 const [data,setData]=useState<Users>();const [q,setQ]=useState('');const [page,setPage]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [mode,setMode]=useState<'invite'|'member'|'academic'|'assign'|null>(null);const [selected,setSelected]=useState<Member>();const [role,setRole]=useState('student');const [status,setStatus]=useState('active');const [email,setEmail]=useState('');const [link,setLink]=useState('');
 const [sections,setSections]=useState<AcademicSection[]>([]);const [departments,setDepartments]=useState<Department[]>([]);const [section,setSection]=useState('');const [active,setActive]=useState(true);const [fields,setFields]=useState<Record<string,string>>({});const [logs,setLogs]=useState<History[]>([]);const [auditPage,setAuditPage]=useState(1);
 const load=useCallback(async()=>{if(!allowed||!id)return;try{const [d,s,dp,l]=await Promise.all([academicRequest<Users>(`/academic-admin/${id}/users?q=${encodeURIComponent(q)}&page=${page}`),api.getSections(id),api.getDepartments(id),academicRequest<History[]>(`/academic-admin/${id}/history?page=${auditPage}`)]);setData(d);setSections(s);setDepartments(dp);setLogs(l);setError('');}catch(e){setError((e as Error).message);}},[id,allowed,q,page,auditPage]);
 useEffect(()=>{void load();},[load]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
   if(mode==='invite'){const r=await academicRequest<{token:string}>(`/academic-admin/${id}/invitations`,'POST',{email,role});setLink(`${window.location.origin}/invitation?token=${encodeURIComponent(r.token)}`);}
   else if(mode==='member'){await academicRequest(`/academic-admin/${id}/users/${selected?.id}`,'PATCH',{role,status});setMode(null);await refreshUser();}
   else if(mode==='assign'){await academicRequest(`/academic-admin/${id}/assignments`,'POST',{user_id:selected?.id,section_id:Number(section),active});setMode(null);}
   else {const body:Record<string,unknown>={...fields};for(const k of ['department_id','year_of_study'])if(k in body)body[k]=body[k]?Number(body[k]):null;await academicRequest(`/academic-admin/${id}/users/${selected?.id}/academic`,'PATCH',body);setMode(null);}
   await load();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!allowed)return <div className="ws-panel"><h1>Administration access required</h1><p>This area is available only to verified university super admins.</p><Link href="/dashboard">Return to dashboard</Link></div>;
 const links=[['Departments','departments'],['Subjects & credits','courses'],['Sections & teaching assignments','sections'],['Academic terms','terms'],['University timetables','timetables'],['Rooms','rooms'],['Official teaching load','analytics']];
 return <><header className="ws-header"><div><div className="ws-kicker">SUPER ADMIN · UNIVERSITY MANAGEMENT</div><h1>Administration</h1><p>Manage academic records and access. Personal schedules remain private.</p></div><button className="ws-button primary" onClick={()=>{setMode('invite');setRole('student');setEmail('');setLink('');}}>Invite user</button></header>
 {error&&<p className="notice error" role="alert">{error}<button onClick={load}>Retry</button></p>}
 <nav className="admin-resource-grid" aria-label="Academic administration">{links.map(([name,path])=><Link className="ws-panel" key={path} href={`/university/${path}`}>{name} →</Link>)}<Link className="ws-panel" href="/classes">Shared classes & announcements →</Link><Link className="ws-panel" href="/appointments">Shared university events →</Link></nav>
 {data?<><div className="weekly-summary"><div><span>ACTIVE STUDENTS</span><strong>{data.students}</strong></div><div><span>ACTIVE PROFESSORS</span><strong>{data.professors}</strong></div><div><span>MATCHING ACCOUNTS</span><strong>{data.total}</strong></div></div>
 <section className="ws-panel"><h2>User management</h2><label className="ws-form">Search university users<input type="search" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Name or email"/></label><div className="ws-scroll"><table className="ws-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.users.map(m=><tr key={m.id}><td>{m.name||'Unnamed'}<br/>{m.email}</td><td>{m.role}</td><td>{m.status}</td><td><div className="ws-actions"><button className="ws-link" onClick={()=>{setSelected(m);setRole(m.role==='faculty'?'professor':m.role);setStatus(m.status);setMode('member');}}>Role & access</button>{['student','professor','faculty'].includes(m.role)&&<><button className="ws-link" onClick={()=>{setSelected(m);setFields({});setMode('academic');academicRequest<Record<string,unknown>>(`/academic-admin/${id}/users/${m.id}/academic`).then(d=>setFields(Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v==null?'':String(v)])))).catch(e=>setError(e.message));}}>Academic record</button><button className="ws-link" onClick={()=>{setSelected(m);setSection('');setActive(true);setMode('assign');}}>Assign</button></>}</div></td></tr>)}</tbody></table></div>{!data.users.length&&<p>No matching users.</p>}<div className="ws-actions"><button className="ws-button" disabled={page===1} onClick={()=>setPage(page-1)}>Previous users</button><span>Page {page}</span><button className="ws-button" disabled={page*20>=data.total} onClick={()=>setPage(page+1)}>Next users</button></div></section></>:<p role="status">Loading administration…</p>}
 <section className="ws-panel" style={{marginTop:24}}><h2>Academic audit history</h2>{logs.map(l=><div className="ws-list-row" key={l.id}><strong>{l.action.replaceAll('_',' ')}</strong><p>{l.detail}</p><small>{l.created_at} · Actor #{l.actor_id}</small></div>)}{!logs.length&&<p>No recorded changes on this page.</p>}<div className="ws-actions"><button className="ws-button" disabled={auditPage===1} onClick={()=>setAuditPage(auditPage-1)}>Newer history</button><button className="ws-button" disabled={logs.length<30} onClick={()=>setAuditPage(auditPage+1)}>Older history</button></div></section>
 {mode&&<Modal title={mode==='invite'?'Invite university user':`${selected?.name||selected?.email} · ${mode}`} onClose={()=>setMode(null)}><form className="ws-form" onSubmit={submit}>
 {(mode==='invite'||mode==='member')&&<><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="student">Student</option><option value="professor">Professor</option>{mode==='member'&&<option value="super_admin">Super admin</option>}</select></label>{mode==='invite'?<><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><p className="ws-muted">The user registers or signs in with this email and accepts the one-time invitation. No password is issued.</p>{link&&<label>Share this invitation privately<textarea readOnly value={link} onFocus={e=>e.target.select()}/></label>}</>:<label>University access<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>}</>}
 {mode==='assign'&&<><label>Section<select required value={section} onChange={e=>setSection(e.target.value)}><option value="">Select section</option>{sections.map(s=><option value={s.id} key={s.id}>{s.section_code} · {s.course_name||s.course_id}</option>)}</select></label><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active assignment (uncheck to remove)</label></>}
 {mode==='academic'&&<><p className="ws-muted">Only edited fields will change. Existing values remain intact.</p><label>Department<select value={fields.department_id||""} onChange={e=>setFields({...fields,department_id:e.target.value})}><option value="" disabled>Select department to update</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{(selected?.role==='student'?['student_number','program','year_of_study']:['employee_code','title']).map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={fields[k]||''} onChange={e=>setFields({...fields,[k]:e.target.value})}/></label>)}</>}
 {error&&<p role="alert" className="notice error">{error}</p>}<button className="ws-button primary" disabled={busy}>{busy?'Saving…':mode==='invite'?'Create invitation':'Save changes'}</button></form></Modal>}
 </>;
}
