'use client';
import {useEffect,useState} from 'react';
import {useAuthContext} from '@/context/AuthContext';
import {academicRequest} from '@/lib/api';
import {Appointment} from '@/lib/academic';
import Modal from './Modal';
const empty:Appointment={title:'',location:'',event_date:'',start_time:'09:00',end_time:'10:00',class_ids:[]};
export default function Appointments(){
 const {memberships}=useAuthContext();const classes=memberships.filter(c=>c.role==='instructor');const [rows,setRows]=useState<Appointment[]>([]);const [form,setForm]=useState<Appointment>();const [share,setShare]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{setRows(await academicRequest<Appointment[]>('/academic/appointments'));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setBusy(true);setError('');try{const {id,...body}=form;await academicRequest(`/academic/appointments${id?`/${id}`:''}`,id?'PUT':'POST',{...body,share_with_students:share});setForm(undefined);await load();window.dispatchEvent(new Event('syncshift:schedule-updated'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(id:number){if(!window.confirm('Delete this appointment for you and its selected audience?'))return;try{await academicRequest(`/academic/appointments/${id}`,'DELETE');await load();}catch(e){setError((e as Error).message);}}
 return <><header className="ws-header"><div><div className="ws-kicker">EXPLICIT AUDIENCES</div><h1>Appointments & sharing</h1><p>Private by default. Share only with classes you manage.</p></div><button className="ws-button primary" onClick={()=>{setForm({...empty});setShare(false);}}>Create appointment</button></header>{error&&<p className="notice error" role="alert">{error}</p>}<div className="class-grid">{rows.map(r=><section className="ws-panel" key={r.id}><span className="ws-badge">{r.class_ids.length?'Shared with selected classes':'Private'}</span><h2>{r.title}</h2><p>{r.event_date} · {r.start_time}–{r.end_time}</p><p className="ws-muted">{r.class_ids.map(id=>memberships.find(c=>c.id===id)?.name||'Former class (access revoked)').join(', ')}</p><div className="ws-actions"><button className="ws-button" onClick={()=>{setForm(r);setShare(!!r.class_ids.length);}}>Edit / stop sharing</button><button className="ws-link" onClick={()=>void remove(r.id!)}>Delete</button></div></section>)}</div>{!rows.length&&<section className="ws-panel ws-empty">No appointments yet. Existing private tasks remain in Calendar and Planner.</section>}
 {form&&<Modal title={form.id?'Edit appointment':'Create appointment'} onClose={()=>setForm(undefined)}><form className="ws-form" onSubmit={save}>{(['title','event_date','start_time','end_time','location'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input required={k!=='location'} maxLength={255} type={k==='event_date'?'date':k.includes('time')?'time':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}{classes.length>0&&<label className="ws-check"><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/> Share with students</label>}{share&&<fieldset><legend>Select intended classes</legend>{classes.map(c=><label className="ws-check" key={c.id}><input type="checkbox" checked={form.class_ids.includes(c.id)} onChange={e=>setForm({...form,class_ids:e.target.checked?[...form.class_ids,c.id]:form.class_ids.filter(id=>id!==c.id)})}/>{c.name}</label>)}</fieldset>}<p className="notice">{share?`Shared audience: ${form.class_ids.map(id=>classes.find(c=>c.id===id)?.name).filter(Boolean).join(', ')||'Select a class before saving'}`:'Only you can see this appointment.'}</p>{error&&<p role="alert" className="notice error">{error}</p>}<button className="ws-button primary" disabled={busy||(share&&!form.class_ids.length)}>{busy?'Saving…':'Save appointment'}</button></form></Modal>}
 </>;
}
