'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {academicRequest} from '@/lib/api';
import {Profile,isProfessor} from '@/lib/academic';
import {useAuthContext} from '@/context/AuthContext';

export default function ProfilePage({userId}:{userId?:string}){
  const {user}=useAuthContext(); const [data,setData]=useState<Profile>(); const [error,setError]=useState(''); const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const [form,setForm]=useState<Record<string,string>>({}); const own=!userId || userId===String(user?.user_id);
  useEffect(()=>{let active=true;academicRequest<Profile>(`/academic/profile/${own?'me':userId}`).then(d=>{if(active){setData(d);setForm({introduction:d.introduction,...d.professional});}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[userId,own]);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setData(await academicRequest<Profile>('/academic/profile/me','PATCH',form));setMessage('Profile saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><header className="ws-header"><div><div className="ws-kicker">{own?'YOUR PROFILE':'PROFESSIONAL PROFILE'}</div><h1>{own?'Profile':'Meet your professor'}</h1></div>{own&&<Link className="ws-button" href="/settings">Account settings</Link>}</header>
    {error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
    {!data?<p>Loading profile…</p>:<><section className="ws-panel profile-header"><div className="profile-cover"/><div className="profile-identity">{data.avatar_url?<img className="profile-photo" src={data.avatar_url} alt={`${data.name}'s profile`}/>:<span className="profile-photo">{(data.name||'S').slice(0,1)}</span>}<h2>{data.name||'Your profile'}</h2><p>{data.affiliations.map(a=>[a.designation,a.department,a.institution].filter(Boolean).join(' · ')).join(' / ')}</p><p className="ws-muted">{data.university_email}</p><p style={{whiteSpace:'pre-wrap'}}>{data.introduction||'No introduction supplied.'}</p></div></section>
      <div className="ws-grid" style={{marginTop:24}}><section className="ws-panel"><h2>{data.affiliations.length?'Professional information':'Academic information'}</h2>{Object.entries(data.professional).filter(([,v])=>v).map(([k,v])=><div className="ws-list-row" key={k}><strong>{k.replaceAll('_',' ')}</strong><p>{v}</p></div>)}{data.academic?.map((a,i)=><div className="ws-list-row" key={i}><h3>{a.university}</h3><p>{a.department} · {a.program}</p><p>Enrollment: {a.enrollment_number||'Not supplied'} · Year: {a.year||'Not supplied'}</p></div>)}{own&&<><p className="ws-muted">Private account: {data.email} · {data.timezone}</p>{data.affiliations.map(a=><p key={a.institution_id}>Staff identifier: {a.staff_identifier||'Not supplied'} (visible only to you here)</p>)}<p className="ws-muted">Your administrator controls academic identity, affiliation and teaching assignments.</p></>}</section>
      <aside className="ws-panel"><h2>{data.affiliations.length?'Subjects taught':'Enrolled sections'}</h2>{data.subjects.map(s=><div className="ws-list-row" key={s.id}>{s.name}</div>)}{data.enrollments?.map((e,i)=><div className="ws-list-row" key={i}><strong>{e.subject}</strong><p>{e.section} · {e.term}</p></div>)}{!data.subjects.length&&!data.enrollments?.length&&<p className="ws-muted">No assigned subjects available.</p>}</aside></div>
      {own&&<form onSubmit={save} className="ws-panel ws-form" style={{marginTop:24}}><h2>Edit {isProfessor(user?.institution_role)?'professional':'personal'} profile</h2><label>Introduction<textarea maxLength={4000} value={form.introduction||''} onChange={e=>setForm({...form,introduction:e.target.value})}/></label>{isProfessor(user?.institution_role)&&['specializations','professional_phone','office_hours','office_location'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input maxLength={k==='professional_phone'?64:k==='office_location'?255:k==='office_hours'?500:1000} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<p className="ws-muted">Professional contact fields are visible to members of your university. Add only a contact number you explicitly want to share professionally. Your account settings stay private.</p><button disabled={busy} className="ws-button primary">{busy?'Saving…':'Save profile'}</button></form>}
    </>}
  </>;
}
