'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {academicRequest,ClassEventInput} from '@/lib/api';
import {Subject,Lecture} from '@/lib/academic';
import Modal from './Modal';
export default function SubjectDetails({classId,instructor}:{classId:number;instructor:boolean}){
 const [data,setData]=useState<Subject>();const [error,setError]=useState('');const [selected,setSelected]=useState<Lecture>();const [status,setStatus]=useState('delivered');const [busy,setBusy]=useState(false);
 const [replacement,setReplacement]=useState<ClassEventInput>({title:'',event_date:'',start_time:'09:00',end_time:'10:00',location:''});
 const load=useCallback(()=>academicRequest<Subject>(`/academic/classes/${classId}`).then(d=>{setData(d);setError('');}).catch(e=>setError(e.message)),[classId]);useEffect(()=>{void load();},[load]);
 async function save(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{setData(await academicRequest<Subject>(`/academic/classes/${classId}/records`,'POST',{event_key:selected.event_key,event_date:selected.date,status,replacement:status==='rescheduled'?replacement:null}));setSelected(undefined);window.dispatchEvent(new Event('syncshift:schedule-updated'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="ws-panel" style={{marginBottom:24}}><h2>Subject & recorded progress</h2>{error&&<p className="notice error" role="alert">{error}<button onClick={load}>Retry</button></p>}{data?<><p>{[data.subject.code,data.subject.department,data.subject.term,data.subject.section].filter(Boolean).join(' · ')}</p><p className="ws-muted">{data.subject.credits===null?'Credits not supplied':`${data.subject.credits} credits`} · {data.subject.introduction||'Introduction not supplied'}</p><div className="weekly-summary"><div><span>PLANNED</span><strong>{data.progress.planned_lectures}<small> lectures · {data.progress.planned_hours}h</small></strong></div><div><span>RECORDED DELIVERED</span><strong>{data.progress.delivered_lectures}<small> lectures · {data.progress.delivered_hours}h</small></strong></div><div><span>REMAINING</span><strong>{data.progress.remaining_lectures}<small> lectures · {data.progress.remaining_hours}h</small></strong></div></div><p className="ws-muted">Past dates do not count as delivered. Completion is recorded explicitly by teaching staff.</p><div className="ws-actions">{data.professors.map(p=><Link className="ws-button" key={p.user_id} href={`/professors/${p.user_id}`}>{p.name} · Profile →</Link>)}</div>
 <details style={{marginTop:20}}><summary>Lecture register ({data.sessions.length} occurrences)</summary><div className="ws-scroll" tabIndex={0} role="region" aria-label="Lecture register table"><table className="ws-table"><thead><tr><th>Lecture</th><th>Date & time</th><th>Recorded state</th>{instructor&&<th>Update</th>}</tr></thead><tbody>{data.sessions.map(s=><tr key={`${s.event_key}-${s.date}`}><td>{s.title}</td><td>{s.date} · {s.start_time}–{s.end_time}</td><td>{s.status}</td>{instructor&&<td><button className="ws-link" disabled={s.status==='rescheduled'} onClick={()=>{setSelected(s);setStatus('delivered');setReplacement({title:s.title,event_date:s.date,start_time:s.start_time,end_time:s.end_time,location:''});}}>Record / reschedule</button></td>}</tr>)}</tbody></table></div></details></>:<p>Loading verified subject information…</p>}
 {selected&&<Modal title="Record lecture outcome" onClose={()=>setSelected(undefined)}><form onSubmit={save} className="ws-form"><p>{selected.title} · {selected.date}</p><label>Outcome<select value={status} onChange={e=>setStatus(e.target.value)}><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option><option value="rescheduled">Rescheduled</option><option value="scheduled">Scheduled (correct a record)</option></select></label>{status==='rescheduled'&&<>{(['event_date','start_time','end_time','location'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input required={k!=='location'} type={k==='event_date'?'date':k.includes('time')?'time':'text'} value={replacement[k]} onChange={e=>setReplacement({...replacement,[k]:e.target.value})}/></label>)}<p className="ws-muted">The original remains in history; the replacement is published to this class.</p></>}{error&&<p role="alert" className="notice error">{error}</p>}<button className="ws-button primary" disabled={busy}>Save outcome</button></form></Modal>}
 </section>;
}
